/home/honeyguide/Desktop/MyOpenSource/facad/src/dir_analytics.h File Reference
Header file for directory analysis functionality.
Functions
void print_dir_analytics (const char *path)
Prints detailed analytics about a directory.
Detailed Description
Header file for directory analysis functionality.
This file contains the declaration of functions for generating and displaying detailed analytics about directory contents. It provides an interface for examining file sizes, counts, timestamps, and other attributes within a directory structure.
Author
Sergey Veneckiy
Date
2024
Definition in file dir_analytics.h.
Function Documentation
print_dir_analytics()
void print_dir_analytics (const char * path)
Prints detailed analytics about a directory.
This function analyzes the contents of the specified directory and prints various statistics including:
Total size of all files
Number of files and directories
Depth of the directory tree
File size ranges (smallest and largest)
Newest and oldest files
File type distributions
Permissions and ownership information
The analytics provide a comprehensive overview of the directory's contents, useful for storage management and content analysis.
Parameters
path The path of the directory to analyze
Note
This function performs a recursive analysis and may take considerable time for large directory structures.
Warning
For very large directories, this function may consume significant memory and processing resources.
This function analyzes the contents of the specified directory and prints various statistics including total size, file counts, directory depth, and information about largest and newest files.
Parameters
path The path of the directory to analyze.
Definition at line 211 of file dir_analytics.c.
                                           {
    DIR* dir;
    struct dirent* entry;
    struct stat st;
    off_t largest_size = 0;
    int total_files = 0, total_dirs = 0, empty_files = 0, max_depth = 0;
    time_t newest_time = 0, oldest_time = time(NULL);
    char largest_file[MAX_PATH] = "", newest_file[MAX_PATH] = "", oldest_file[MAX_PATH] = "";
    char empty_file_names[MAX_FILES][256];
    char deepest_dir[MAX_PATH] = "";
    dir = opendir(path);
    if (!dir) {
        perror("Error opening directory");
        return;
    }
    // Find the largest file recursively
    find_largest_file(path, &largest_size, largest_file, sizeof(largest_file));
    // Calculate total size recursively
    off_t total_size = calculate_total_size(path);
    while ((entry = readdir(dir)) != NULL) {
        char full_path[MAX_PATH];
        snprintf(full_path, sizeof(full_path), "%s/%s", path, entry->d_name);
        if (lstat(full_path, &st) != 0) continue;
        if (strcmp(entry->d_name, ".") == 0 || strcmp(entry->d_name, "..") == 0) continue;
        if (S_ISDIR(st.st_mode)) {
            total_dirs++;
        } else if (S_ISREG(st.st_mode)) {
            total_files++;
            // Check for largest file
            if (st.st_size > largest_size) {
                largest_size = st.st_size;
                strncpy(largest_file, entry->d_name, sizeof(largest_file) - 1);
            }
            // Check for newest file
            if (st.st_mtime > newest_time) {
                newest_time = st.st_mtime;
                strncpy(newest_file, entry->d_name, sizeof(newest_file) - 1);
            }
            // Check for oldest file
            if (st.st_mtime < oldest_time) {
                oldest_time = st.st_mtime;
                strncpy(oldest_file, entry->d_name, sizeof(oldest_file) - 1);
            }
            // Check for empty files
            if (st.st_size == 0) {
                strncpy(empty_file_names[empty_files], entry->d_name, 255);
                empty_file_names[empty_files][255] = '\0';
                empty_files++;
            }
        }
    }
    closedir(dir);
    // Calculate max depth and find deepest directory
    recursive_dir_scan(path, &max_depth, 0, deepest_dir);
    char cwd[MAX_PATH];
    if (getcwd(cwd, sizeof(cwd)) == NULL) {
        perror("getcwd() error");
        return;
    }
    // Print analytics
    printf("%s%s%s\n", ANSI_BOLD, cwd, ANSI_RESET);
    printf("🧮 Total Size : %s\n", format_size(total_size));
    printf("🗂️ Directories : %d\n", total_dirs);
    printf("🌳 Max Depth : %d levels\n", max_depth);
    printf("📁 Deepest Dir : %s\n", deepest_dir);
    printf("🗃️ Files : %d\n", total_files);
    printf("🐘 Largest File : %s [%s]\n", largest_file, format_size(largest_size));
    printf("🏺 Oldest File : %s [%s]\n", oldest_file, format_time(oldest_time));
    printf("🆕 Newest File : %s [%s]\n", newest_file, format_time(newest_time));
    printf("📭 Empty Files : %d [", empty_files);
    // Print names of empty files
    for (int i = 0; i < empty_files; i++) {
        printf("%s%s", empty_file_names[i], (i + 1 < empty_files) ? " " : "");
    }
    printf("]\n");
}
References ANSI_BOLD, ANSI_RESET, calculate_total_size(), find_largest_file(), format_size(), format_time(), MAX_FILES, MAX_PATH, and recursive_dir_scan().
Referenced by main().