/home/honeyguide/Desktop/MyOpenSource/facad/src/longlisting.h File Reference
Functions
void print_longlisting (const char *path)
Prints a detailed listing of the contents of a directory.
void print_longlisting_files (const char **patterns, int pattern_count)
Function Documentation
print_longlisting()
void print_longlisting (const char * path)
Prints a detailed listing of the contents of a directory.
Parameters
path The path of the directory to list.
Definition at line 306 of file longlisting.c.
                                         {
    setlocale(LC_ALL, "");
    struct file_info entries[MAX_ENTRIES];
    int entry_count = 0;
    size_t max_owner_len = 0;
    size_t max_time_ago_len = 0;
    DIR *dir = opendir(path);
    if (!dir) {
        perror("Error opening directory");
        return;
    }
    struct dirent *entry;
    while ((entry = readdir(dir)) != NULL && entry_count < MAX_ENTRIES) {
        if (strcmp(entry->d_name, ".") == 0 || strcmp(entry->d_name, "..") == 0) continue;
        char full_path[MAX_PATH];
        snprintf(full_path, sizeof(full_path), "%s/%s", path, entry->d_name);
        struct file_info *fi = &entries[entry_count];
        if (get_file_info(full_path, fi, &max_owner_len, &max_time_ago_len) == 0) {
            entry_count++;
        }
    }
    closedir(dir);
    qsort(entries, entry_count, sizeof(struct file_info), compare_entries);
    print_sorted_entries(entries, entry_count, max_owner_len, max_time_ago_len);
}
References compare_entries(), file_info::full_path, get_file_info(), MAX_ENTRIES, MAX_PATH, and print_sorted_entries().
Referenced by main().
print_longlisting_files()
void print_longlisting_files (const char ** patterns, int pattern_count)
Definition at line 339 of file longlisting.c.
                                                                       {
    struct file_info entries[MAX_ENTRIES];
    int entry_count = 0;
    size_t max_owner_len = 0;
    size_t max_time_ago_len = 0;
    for (int i = 0; i < pattern_count; i++) {
        glob_t globbuf;
        int glob_result = glob(patterns[i], GLOB_TILDE, NULL, &globbuf);
        if (glob_result == 0) {
            for (size_t j = 0; j < globbuf.gl_pathc && entry_count < MAX_ENTRIES; j++) {
                struct file_info *fi = &entries[entry_count];
                if (get_file_info(globbuf.gl_pathv[j], fi, &max_owner_len, &max_time_ago_len) == 0) {
                    entry_count++;
                }
            }
        } else {
            fprintf(stderr, "glob error for pattern '%s': %s\n", patterns[i], strerror(errno));
        }
        globfree(&globbuf);
    }
    if (entry_count > 0) {
        qsort(entries, entry_count, sizeof(struct file_info), compare_entries);
        print_sorted_entries(entries, entry_count, max_owner_len, max_time_ago_len);
    } else {
        fprintf(stderr, "No matching files found.\n");
    }
}
References compare_entries(), get_file_info(), MAX_ENTRIES, and print_sorted_entries().
Referenced by main().