/home/honeyguide/Desktop/MyOpenSource/facad/src/display_utils.c File Reference
Implementation of display utilities for file entries.
#include <glob.h>
#include <stdio.h>
#include <wchar.h>
#include <string.h>
#include <stdlib.h>
#include <locale.h>
#include "file_card.h"
#include "git_utils.h"
#include "dir_config.h"
#include "display_utils.h"
Macros
#define _XOPEN_SOURCE 700
#define MAX_COLUMNS 4
#define SPACING 2
#define EMOJI_WIDTH 2
#define EMOJI_NAME_SPACING 1
Functions
size_t get_utf8_char_width (const char *str)
Determines the byte width of a UTF-8 character.
size_t get_display_width (const char *str)
Calculates the display width of a string, accounting for multi-byte characters.
void print_padded (const char *str, size_t width)
Prints a string and pads it with spaces to reach the specified width.
void display_entries (FileCardInfo *entries, int num_entries, int term_width, const char *current_dir, int show_path)
Displays file entries in a formatted, multi-column layout.
Detailed Description
Implementation of display utilities for file entries.
This file contains functions for formatting and displaying file entries in a grid layout, taking into account terminal width and Unicode characters. It handles the visual representation of directory contents, including emojis, Git status, and proper spacing.
Author
Sergey Veneckiy
Date
2024
Definition in file display_utils.c.
Macro Definition Documentation
_XOPEN_SOURCE
#define _XOPEN_SOURCE 700
Definition at line 15 of file display_utils.c.
EMOJI_NAME_SPACING
#define EMOJI_NAME_SPACING 1
Definition at line 33 of file display_utils.c.
Referenced by display_entries().
EMOJI_WIDTH
#define EMOJI_WIDTH 2
Definition at line 32 of file display_utils.c.
Referenced by display_entries().
MAX_COLUMNS
#define MAX_COLUMNS 4
Definition at line 30 of file display_utils.c.
SPACING
#define SPACING 2
Definition at line 31 of file display_utils.c.
Referenced by display_entries().
Function Documentation
display_entries()
void display_entries (FileCardInfo * entries, int num_entries, int term_width, const char * current_dir, int show_path)
Displays file entries in a formatted, multi-column layout.
This function sorts the entries, calculates the appropriate layout based on terminal width, and prints the entries in a grid format. It handles emojis, Git status, and ensures proper alignment.
Parameters
entries Array of FileCardInfo structures to display.
num_entries Number of entries in the array.
term_width Width of the terminal in characters.
current_dir Current directory path.
show_path Flag to indicate whether to show the current path.
Definition at line 108 of file display_utils.c.
                                                             {
    setlocale(LC_ALL, ""); // Set the locale for proper Unicode handling
    // Display the current directory and Git branch if requested
    if (show_path) {
        char *branch = get_current_branch();
        if (branch) {
            //printf("\033[1m%s\033[0m (\033[32m%s\033[0m)\n", current_dir, branch);
            printf("\033[1m%s\033[0m \033[38;5;202m[%s]\033[0m\n", current_dir, branch);
            free(branch);
        } else {
            printf("\033[1m%s\033[0m\n", current_dir);
        }
    }
    // Allocate memory for storing entry widths
    size_t *entry_widths = malloc(num_entries * sizeof(size_t));
    if (!entry_widths) {
        fprintf(stderr, "Memory allocation failed\n");
        return;
    }
    // Calculate the width of each entry and find the maximum width
    size_t max_width = 0;
    for (int i = 0; i < num_entries; i++) {
        // Calculate width: emoji + spacing + name + potential Git status
        entry_widths[i] = EMOJI_WIDTH + EMOJI_NAME_SPACING + get_display_width(entries[i].name);
        if (entries[i].git_status[0] != '\0') {
            entry_widths[i] += 3; // Add 3 for "(X)" Git status
        }
        if (entry_widths[i] > max_width) {
            max_width = entry_widths[i];
        }
    }
    // Calculate the number of columns based on terminal width
    int num_columns = (term_width + SPACING) / (max_width + SPACING);
    int max_columns = get_max_columns(current_dir);
    if (num_columns > max_columns) num_columns = max_columns;
    if (num_columns < 1) num_columns = 1;
    // Allocate memory for column widths
    size_t *column_widths = calloc(num_columns, sizeof(size_t));
    if (!column_widths) {
        fprintf(stderr, "Memory allocation failed\n");
        free(entry_widths);
        return;
    }
    // Calculate the number of rows
    int rows = (num_entries + num_columns - 1) / num_columns;
    // Calculate the width of each column
    for (int i = 0; i < num_entries; i++) {
        int col = i / rows;
        if (entry_widths[i] > column_widths[col]) {
            column_widths[col] = entry_widths[i];
        }
    }
    // Display the entries in a grid format
    for (int row = 0; row < rows; row++) {
        for (int col = 0; col < num_columns; col++) {
            int index = col * rows + row;
            if (index < num_entries) {
                // Print emoji
                printf("%s ", entries[index].emoji);
                // Print file name
                printf("%s", entries[index].name);
                // Print Git status if available
                if (entries[index].git_status[0] != '\0') {
                    //printf("(\033[32m%c\033[0m)", entries[index].git_status[0]);
                    printf("\033[38;5;202m[%c]\033[0m", entries[index].git_status[0]);
                }
                // Calculate and print padding
                size_t printed_width = entry_widths[index];
                size_t padding = (col < num_columns - 1) ? column_widths[col] - printed_width + SPACING : 0;
                for (size_t i = 0; i < padding; i++) {
                    printf(" ");
                }
            }
        }
        printf("\n"); // Move to the next row
    }
    // Free allocated memory
    free(entry_widths);
    free(column_widths);
}
References EMOJI_NAME_SPACING, EMOJI_WIDTH, get_current_branch(), get_display_width(), get_max_columns(), and SPACING.
Referenced by main().
get_display_width()
size_t get_display_width (const char * str)
Calculates the display width of a string, accounting for multi-byte characters.
This function iterates through the string, determining the width of each character and summing them to get the total display width.
Parameters
str The string to measure.
Returns
The display width of the string.
Definition at line 61 of file display_utils.c.
                                          {
    size_t width = 0;
    while (*str) { // Loop through each character in the string
        size_t char_width = get_utf8_char_width(str); // Get the byte width of the current character
        if (char_width == 4) {
            width += 2; // Emoji and other wide characters count as 2 display units
        } else if (char_width > 1) {
            width += 1; // Other multi-byte characters count as 1 display unit
        } else {
            width += 1; // ASCII characters count as 1 display unit
        }
        str += char_width; // Move to the next character
    }
    return width;
}
References get_utf8_char_width().
Referenced by display_entries(), and print_padded().
get_utf8_char_width()
size_t get_utf8_char_width (const char * str)
Determines the byte width of a UTF-8 character.
This function analyzes the first byte of a UTF-8 character to determine its total byte width.
Parameters
str Pointer to the start of a UTF-8 character.
Returns
The number of bytes used by the character (1-4).
Definition at line 44 of file display_utils.c.
                                            {
    unsigned char c = (unsigned char)*str; // Get the first byte of the character
    if (c < 0x80) return 1; // ASCII character (0xxxxxxx)
    if (c < 0xE0) return 2; // 2-byte UTF-8 character (110xxxxx)
    if (c < 0xF0) return 3; // 3-byte UTF-8 character (1110xxxx)
    return 4; // 4-byte UTF-8 character (11110xxx)
}
Referenced by get_display_width().
print_padded()
void print_padded (const char * str, size_t width)
Prints a string and pads it with spaces to reach the specified width.
This function prints the given string and adds space padding to ensure consistent column widths in the display.
Parameters
str The string to print.
width The total width to fill, including the string and padding.
Definition at line 86 of file display_utils.c.
                                                 {
    size_t str_width = get_display_width(str); // Get the display width of the string
    printf("%s", str); // Print the string
    // Add padding spaces
    for (size_t i = str_width; i < width; i++) {
        printf(" ");
    }
}
References get_display_width().