/home/honeyguide/Desktop/MyOpenSource/facad/src/git_utils.h File Reference
Header file for Git utility functions used in facad.
#include <stdbool.h>
Classes
struct GitFile
Structure to hold information about a single file's Git status.
struct GitFileList
Structure to hold Git status information for multiple files.
Macros
#define MAX_FILENAME 1024
#define MAX_FILES 1000
Functions
bool is_git_repository (void)
Checks if the current directory is part of a Git repository.
GitFileList get_git_status (void)
Retrieves the Git status for all files in the current repository.
char * get_current_branch (void)
Retrieves the name of the current Git branch.
Detailed Description
Header file for Git utility functions used in facad.
This file declares structures and functions for interacting with Git repositories. It provides functionality to check if a directory is a Git repository, retrieve Git status information, and get the current branch name.
Author
Sergey Veneckiy
Date
2024
Definition in file git_utils.h.
Macro Definition Documentation
MAX_FILENAME
#define MAX_FILENAME 1024
Definition at line 18 of file git_utils.h.
Referenced by get_git_status(), and integrate_git_status().
MAX_FILES
#define MAX_FILES 1000
Definition at line 19 of file git_utils.h.
Function Documentation
get_current_branch()
char * get_current_branch (void)
Retrieves the name of the current Git branch.
This function gets the name of the current Git branch in the repository.
Returns
Dynamically allocated string containing the branch name, or NULL if an error occurred.
Note
The caller is responsible for freeing the returned string.
This function executes 'git rev-parse' command to get the name of the current Git branch.
Returns
Dynamically allocated string containing the branch name, or NULL if an error occurred.
Note
The caller is responsible for freeing the returned string.
Definition at line 100 of file git_utils.c.
                           {
    // Execute 'git rev-parse' command to get the branch name
    FILE* fp = popen("git rev-parse --abbrev-ref HEAD 2>/dev/null", "r");
    if (fp == NULL) {
        return NULL; // Return NULL if command execution failed
    }
    char* branch = malloc(256); // Allocate memory for the branch name
    if (fgets(branch, 256, fp) == NULL) { // Read the branch name
        free(branch); // Free allocated memory if read failed
        pclose(fp); // Close the command pipe
        return NULL; // Return NULL to indicate failure
    }
    pclose(fp); // Close the command pipe
    branch[strcspn(branch, "\n")] = 0; // Remove newline character
    return branch; // Return the branch name
}
Referenced by display_entries().
get_git_status()
GitFileList get_git_status (void)
Retrieves the Git status for all files in the current repository.
This function gets the status of all files in the current Git repository, including untracked, modified, and staged files.
Returns
GitFileList structure containing the status of all files in the repository.
This function executes 'git status' command and parses its output to create a list of files with their corresponding Git status.
Returns
GitFileList structure containing the status of all files in the repository.
Definition at line 65 of file git_utils.c.
                             {
    GitFileList list = {0}; // Initialize an empty GitFileList
    // Execute 'git status' command
    FILE* fp = popen("git status -s", "r");
    if (fp == NULL) {
        return list; // Return empty list if command execution failed
    }
    char line[MAX_FILENAME + 3]; // Buffer to store each line of output
    // Read each line of the command output
    while (fgets(line, sizeof(line), fp) != NULL && list.count < MAX_FILES) {
        if (strlen(line) > 3) { // Ensure the line has enough characters
            GitFile file;
            file.status = parse_status(line); // Parse the status
            // Copy the filename, skipping the first 3 characters (status and space)
            strncpy(file.filename, line + 3, MAX_FILENAME - 1);
            file.filename[strcspn(file.filename, "\n")] = 0; // Remove newline
            list.files[list.count++] = file; // Add file to the list
        }
    }
    pclose(fp); // Close the command pipe
    return list; // Return the populated list
}
References GitFileList::count, GitFile::filename, GitFileList::files, MAX_FILENAME, MAX_FILES, parse_status(), and GitFile::status.
Referenced by integrate_git_status(), and main().
is_git_repository()
bool is_git_repository (void)
Checks if the current directory is part of a Git repository.
This function determines whether the current working directory is within a Git repository.
Returns
true if the current directory is in a Git repository, false otherwise.
This function executes the 'git rev-parse' command to determine if the current working directory is within a Git repository.
Returns
true if the current directory is in a Git repository, false otherwise.
Definition at line 28 of file git_utils.c.
                         {
    // Execute 'git rev-parse' command and redirect output to /dev/null
    FILE* fp = popen("git rev-parse --is-inside-work-tree 2>/dev/null", "r");
    if (fp == NULL) {
        return false; // Return false if command execution failed
    }
    char buffer[128]; // Buffer to store command output
    // Read command output and check if it's "true"
    bool result = fgets(buffer, sizeof(buffer), fp) != NULL && strcmp(buffer, "true\n") == 0;
    pclose(fp); // Close the command pipe
    return result; // Return the result
}
Referenced by integrate_git_status(), and main().