/home/honeyguide/Desktop/MyOpenSource/facad/src/file_card.c File Reference
Implementation of file card handling functions.
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <ctype.h>
#include "emoji_utils.h"
#include "file_card.h"
Functions
int create_file_entry (FileCardInfo *entry, const char *path)
Creates a new file card based on the given path.
void free_file_entry (FileCardInfo *entry)
Frees memory allocated for a file entry.
char * get_extension (const char *name)
Extracts the file extension from a filename.
static int strcasecmp_wrapper (const char *a, const char *b)
Compare two strings case-insensitively.
int compare_file_entries (const void *a, const void *b)
Compare two file entries for sorting.
Detailed Description
Implementation of file card handling functions.
This file contains functions for creating, freeing, and comparing file entries, as well as utility functions for working with file names and extensions. It provides the core functionality for managing file information in the facad tool.
Author
Sergey Veneckiy
Date
2024
Definition in file file_card.c.
Function Documentation
compare_file_entries()
int compare_file_entries (const void * a, const void * b)
Compare two file entries for sorting.
Compares two file entries for sorting purposes.
This function implements the sorting logic for file entries:
Directories before files
Within directories and files, dotfiles (hidden) before non-dotfiles
Files sorted by extension
Alphabetical sorting within the same type and extension
Parameters
a Pointer to the first FileCardInfo structure.
b Pointer to the second FileCardInfo structure.
Returns
An integer less than, equal to, or greater than zero if a is found, respectively, to be less than, to match, or be greater than b.
Definition at line 134 of file file_card.c.
{
    const FileCardInfo *entry_a = (const FileCardInfo *)a;
    const FileCardInfo *entry_b = (const FileCardInfo *)b;
    // Sort directories before files
    if (entry_a->is_directory != entry_b->is_directory) {
        return entry_b->is_directory - entry_a->is_directory;
    }
    // For directories, sort dotfiles first
    if (entry_a->is_directory && entry_b->is_directory) {
        // Check if one is a dotfile and the other isn't
        if ((entry_a->name[0] == '.') != (entry_b->name[0] == '.')) {
            return (entry_b->name[0] == '.') - (entry_a->name[0] == '.');
        }
        // Both are either dotfiles or non-dotfiles, sort alphabetically
        return strcasecmp_wrapper(entry_a->name, entry_b->name);
    }
    // For files, sort dotfiles first
    if ((entry_a->name[0] == '.') != (entry_b->name[0] == '.')) {
        return (entry_b->name[0] == '.') - (entry_a->name[0] == '.');
    }
    // Sort files by extension
    const char *ext_a = get_extension(entry_a->name);
    const char *ext_b = get_extension(entry_b->name);
    int ext_cmp = strcasecmp_wrapper(ext_a, ext_b);
    // If extensions differ, return their comparison result
    if (ext_cmp != 0) {
        return ext_cmp;
    }
    // If extensions are the same, sort alphabetically by name
    return strcasecmp_wrapper(entry_a->name, entry_b->name);
}
References get_extension(), FileCardInfo::is_directory, FileCardInfo::name, and strcasecmp_wrapper().
Referenced by main().
create_file_entry()
int create_file_entry (FileCardInfo * entry, const char * path)
Creates a new file card based on the given path.
Creates a file entry based on the given path.
This function initializes a FileCardInfo structure with information about the file, including its name, emoji representation, and flags for directory and hidden status.
Parameters
entry Pointer to a FileCardInfo structure to be filled.
path Path of the file to analyze.
Returns
0 on success, -1 on error.
Definition at line 31 of file file_card.c.
{
    // Duplicate the file name and store it in the entry
    entry->name = strdup(path);
    // Get the appropriate emoji for the file
    entry->emoji = get_emoji(path);
    struct stat path_stat;
    // Get file status information
    if (lstat(path, &path_stat) != 0)
    {
        return -1; // Return -1 if unable to get file status
    }
    // Set directory flag based on file type
    entry->is_directory = S_ISDIR(path_stat.st_mode);
    // Set hidden flag if the file name starts with a dot
    entry->is_hidden = (path[0] == '.');
    // Initialize Git status as empty
    entry->git_status[0] = '\0';
    entry->git_status[1] = '\0';
    return 0; // Return 0 on success
}
References FileCardInfo::emoji, get_emoji(), FileCardInfo::git_status, FileCardInfo::is_directory, FileCardInfo::is_hidden, and FileCardInfo::name.
Referenced by process_directory(), process_files_or_patterns(), and process_target().
free_file_entry()
void free_file_entry (FileCardInfo * entry)
Frees memory allocated for a file entry.
Frees the memory allocated for a file entry.
This function releases the memory allocated for the name and emoji fields of a FileCardInfo structure.
Parameters
entry Pointer to the FileCardInfo structure to free.
Definition at line 64 of file file_card.c.
{
    free(entry->name); // Free the memory allocated for the name string
    free(entry->emoji); // Free the memory allocated for the emoji string
}
References FileCardInfo::emoji, and FileCardInfo::name.
Referenced by main().
get_extension()
char * get_extension (const char * name)
Extracts the file extension from a filename.
This function finds the last occurrence of a dot in the filename and returns the substring following it as the file extension.
Parameters
name The filename to analyze.
Returns
A pointer to the file extension, or an empty string if no extension is found.
Definition at line 79 of file file_card.c.
{
    char *dot = strrchr(name, '.'); // Find the last occurrence of '.'
    if (!dot || dot == name)
    { // If no '.' found or it's the first character
        return ""; // Return empty string (no extension)
    }
    return dot + 1; // Return pointer to character after the last '.'
}
Referenced by compare_file_entries().
strcasecmp_wrapper()
static int strcasecmp_wrapper (const char * a, const char * b) [static]
Compare two strings case-insensitively.
This function provides a case-insensitive string comparison, similar to strcasecmp, but implemented for portability.
Parameters
a The first string to compare.
b The second string to compare.
Returns
An integer less than, equal to, or greater than zero if a is found, respectively, to be less than, to match, or be greater than b.
Definition at line 100 of file file_card.c.
                                                            {
    // Loop continues as long as both strings have characters
    while (*a && *b) {
        // Convert current characters to lowercase for case-insensitive comparison
        int ca = tolower((unsigned char)*a);
        int cb = tolower((unsigned char)*b);
        // If characters differ, return their difference (determines sorting order)
        if (ca != cb) return ca - cb;
        // Move to the next character in both strings
        a++;
        b++;
    }
    // If we've reached here, one string might be longer than the other
    // Compare the last characters (one might be '\0' if strings are different lengths)
    return tolower((unsigned char)*a) - tolower((unsigned char)*b);
}
Referenced by compare_file_entries().