/home/honeyguide/Desktop/MyOpenSource/facad/src/display_utils.h File Reference
#include "file_card.h"
Functions
void display_entries (FileCardInfo *entries, int num_entries, int term_width, const char *current_dir, int show_path)
Displays file entries in a formatted, multi-column layout.
Function Documentation
display_entries()
void display_entries (FileCardInfo * entries, int num_entries, int term_width, const char * current_dir, int show_path)
Displays file entries in a formatted, multi-column layout.
This function sorts the entries, calculates the appropriate layout based on terminal width, and prints the entries in a grid format. It handles emojis, Git status, and ensures proper alignment.
Parameters
entries Array of FileCardInfo structures to display.
num_entries Number of entries in the array.
term_width Width of the terminal in characters.
current_dir Current directory path.
show_path Flag to indicate whether to show the current path.
Definition at line 108 of file display_utils.c.
                                                             {
    setlocale(LC_ALL, ""); // Set the locale for proper Unicode handling
    // Display the current directory and Git branch if requested
    if (show_path) {
        char *branch = get_current_branch();
        if (branch) {
            //printf("\033[1m%s\033[0m (\033[32m%s\033[0m)\n", current_dir, branch);
            printf("\033[1m%s\033[0m \033[38;5;202m[%s]\033[0m\n", current_dir, branch);
            free(branch);
        } else {
            printf("\033[1m%s\033[0m\n", current_dir);
        }
    }
    // Allocate memory for storing entry widths
    size_t *entry_widths = malloc(num_entries * sizeof(size_t));
    if (!entry_widths) {
        fprintf(stderr, "Memory allocation failed\n");
        return;
    }
    // Calculate the width of each entry and find the maximum width
    size_t max_width = 0;
    for (int i = 0; i < num_entries; i++) {
        // Calculate width: emoji + spacing + name + potential Git status
        entry_widths[i] = EMOJI_WIDTH + EMOJI_NAME_SPACING + get_display_width(entries[i].name);
        if (entries[i].git_status[0] != '\0') {
            entry_widths[i] += 3; // Add 3 for "(X)" Git status
        }
        if (entry_widths[i] > max_width) {
            max_width = entry_widths[i];
        }
    }
    // Calculate the number of columns based on terminal width
    int num_columns = (term_width + SPACING) / (max_width + SPACING);
    int max_columns = get_max_columns(current_dir);
    if (num_columns > max_columns) num_columns = max_columns;
    if (num_columns < 1) num_columns = 1;
    // Allocate memory for column widths
    size_t *column_widths = calloc(num_columns, sizeof(size_t));
    if (!column_widths) {
        fprintf(stderr, "Memory allocation failed\n");
        free(entry_widths);
        return;
    }
    // Calculate the number of rows
    int rows = (num_entries + num_columns - 1) / num_columns;
    // Calculate the width of each column
    for (int i = 0; i < num_entries; i++) {
        int col = i / rows;
        if (entry_widths[i] > column_widths[col]) {
            column_widths[col] = entry_widths[i];
        }
    }
    // Display the entries in a grid format
    for (int row = 0; row < rows; row++) {
        for (int col = 0; col < num_columns; col++) {
            int index = col * rows + row;
            if (index < num_entries) {
                // Print emoji
                printf("%s ", entries[index].emoji);
                // Print file name
                printf("%s", entries[index].name);
                // Print Git status if available
                if (entries[index].git_status[0] != '\0') {
                    //printf("(\033[32m%c\033[0m)", entries[index].git_status[0]);
                    printf("\033[38;5;202m[%c]\033[0m", entries[index].git_status[0]);
                }
                // Calculate and print padding
                size_t printed_width = entry_widths[index];
                size_t padding = (col < num_columns - 1) ? column_widths[col] - printed_width + SPACING : 0;
                for (size_t i = 0; i < padding; i++) {
                    printf(" ");
                }
            }
        }
        printf("\n"); // Move to the next row
    }
    // Free allocated memory
    free(entry_widths);
    free(column_widths);
}
References EMOJI_NAME_SPACING, EMOJI_WIDTH, get_current_branch(), get_display_width(), get_max_columns(), and SPACING.
Referenced by main().