/home/honeyguide/Desktop/MyOpenSource/facad/src/emoji_utils.h File Reference
Utility functions for assigning emojis to files and directories.
Functions
char * get_emoji (const char *path)
Determines the appropriate emoji for a given file path.
int is_executable (const char *path)
Checks if a file is executable.
int is_text_file (const char *path)
Checks if a file is a text file.
char * get_dev_emoji (const char *path)
Determines the appropriate emoji for a device file in the /dev directory.
Detailed Description
Utility functions for assigning emojis to files and directories.
This header file declares functions for determining appropriate emojis based on file types, attributes, and locations. It supports both regular files and special files in the /dev directory.
Author
Sergey Veneckiy
Date
2024
Definition in file emoji_utils.h.
Function Documentation
get_dev_emoji()
char * get_dev_emoji (const char * path)
Determines the appropriate emoji for a device file in the /dev directory.
This function analyzes the name of a file in the /dev directory and returns an emoji representing its device type.
Parameters
path The file name in the /dev directory to analyze.
Returns
A dynamically allocated string containing the emoji. The caller is responsible for freeing this memory.
Determines the appropriate emoji for a device file in the /dev directory.
Parameters
path The name of the file in the /dev directory
Returns
A dynamically allocated string containing the emoji
Definition at line 45 of file emoji_utils.c.
                                      {
    // Check for exact matches in the dev file map
    for (size_t i = 0; i < sizeof(emoji_exact_dev_file_map_size); i++) {
        if (strcmp(path, emoji_exact_dev_file_map[i].key) == 0) {
            return safe_strdup(emoji_exact_dev_file_map[i].emoji);
        }
    }
    // Check for prefix matches in the dev prefix map
    for (size_t i = 0; i < emoji_prefix_dev_map_size; i++) {
        if (strncmp(path, emoji_prefix_dev_map[i].key, strlen(emoji_prefix_dev_map[i].key)) == 0) {
            return safe_strdup(emoji_prefix_dev_map[i].emoji);
        }
    }
    // Return default emoji for unmatched /dev files
    return safe_strdup("ðŸ”§");
}
References emoji_exact_dev_file_map, emoji_exact_dev_file_map_size, emoji_prefix_dev_map, emoji_prefix_dev_map_size, and safe_strdup().
Referenced by handle_dev_directory().
get_emoji()
char * get_emoji (const char * path)
Determines the appropriate emoji for a given file path.
This function analyzes the file at the given path and returns an emoji representing its type (e.g., directory, text file, image, etc.).
Parameters
path The file path to analyze.
Returns
A dynamically allocated string containing the emoji. The caller is responsible for freeing this memory.
Determines the appropriate emoji for a given file path.
Parameters
path The path to the file
Returns
A dynamically allocated string containing the emoji
Definition at line 95 of file emoji_utils.c.
                                  {
   struct stat path_stat;
    // Check if we can get file information
    if (lstat(path, &path_stat) != 0) {
        return safe_strdup("â“"); // Unknown file type
    }
    // Check for symbolic links
    if (S_ISLNK(path_stat.st_mode)) {
        return safe_strdup(S_ISDIR(path_stat.st_mode) ? "ðŸ”—ðŸ“" : "ðŸ”—");
    }
    // Check for directories
    if (S_ISDIR(path_stat.st_mode)) {
        return safe_strdup("ðŸ“");
    }
    // Extract the filename from the path
    const char *filename = strrchr(path, '/');
    filename = filename ? filename + 1 : path;
    // Check for exact file name matches first (highest priority)
    for (size_t i = 0; i < emoji_exact_file_map_size; i++) {
        if (strcasecmp(filename, emoji_exact_file_map[i].key) == 0) {
            return safe_strdup(emoji_exact_file_map[i].emoji);
        }
    }
    // Check file content for specific patterns (second priority)
    char *content_emoji = check_file_content(path);
    if (content_emoji) {
        return content_emoji;
    }
    // Check file extensions (third priority)
    char *extension = strrchr(filename, '.');
    if (extension) {
        extension++; // Skip the dot
        for (size_t i = 0; i < emoji_extension_map_size; i++) {
            if (strcasecmp(extension, emoji_extension_map[i].key) == 0) {
                return safe_strdup(emoji_extension_map[i].emoji);
            }
        }
    }
    // Check for hidden files
    if (filename[0] == '.') {
        return safe_strdup("âš™ï¸");
    }
    // Check for executable files
    if (is_executable(path)) {
        return safe_strdup("ðŸ’¾");
    }
    // Check for text files
    if (is_text_file(path)) {
        return safe_strdup("ðŸ“");
    }
    // Default emoji for unclassified files
    return safe_strdup("â“");
}
References check_file_content(), emoji_exact_file_map, emoji_exact_file_map_size, emoji_extension_map, emoji_extension_map_size, is_executable(), is_text_file(), and safe_strdup().
Referenced by create_file_entry(), and print_sorted_entries().
is_executable()
int is_executable (const char * path)
Checks if a file is executable.
This function determines whether the file at the given path has execute permissions.
Parameters
path The file path to check.
Returns
1 if the file is executable, 0 otherwise.
Parameters
path The path to the file
Returns
1 if the file is executable, 0 otherwise
Definition at line 166 of file emoji_utils.c.
                                    {
    struct stat st;
    if (stat(path, &st) == 0) {
        return (st.st_mode & S_IXUSR) != 0; // Check if the user execute bit is set
    }
    return 0;
}
Referenced by get_emoji().
is_text_file()
int is_text_file (const char * path)
Checks if a file is a text file.
This function analyzes the content of the file to determine if it's likely to be a text file.
Parameters
path The file path to check.
Returns
1 if the file is likely a text file, 0 otherwise.
Checks if a file is a text file.
Parameters
path The path to the file
Returns
1 if the file is likely a text file, 0 otherwise
Definition at line 180 of file emoji_utils.c.
                                   {
    FILE *file = fopen(path, "rb");
    if (!file) {
        return 0; // Cannot open file, assume it's not text
    }
    unsigned char buffer[1024];
    size_t bytesRead = fread(buffer, 1, sizeof(buffer), file);
    fclose(file);
    if (bytesRead == 0) {
        return 1; // Empty file is considered text
    }
    // Check if all read bytes are printable or whitespace
    for (size_t i = 0; i < bytesRead; i++) {
        if (!isprint(buffer[i]) && !isspace(buffer[i])) {
            return 0; // Non-printable, non-whitespace character found
        }
    }
    return 1; // All characters are printable or whitespace
}
Referenced by get_emoji().