/home/honeyguide/Desktop/MyOpenSource/facad/src/args_parser.c File Reference
Implementation of command-line argument parsing for facad.
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include "config.h"
#include "args_parser.h"
Functions
bool is_glob_pattern (const char *str)
Checks if a string is a glob pattern.
CommandLineArgs parse_args (int argc, char *argv[])
Parses command-line arguments.
void free_args (CommandLineArgs *args)
Frees memory allocated for command-line arguments.
void print_version (void)
Prints the version information of facad.
void print_help (const char *program_name)
Prints the help information for facad.
Detailed Description
Implementation of command-line argument parsing for facad.
This file contains functions for parsing command-line arguments, identifying options, and handling version and help requests. It also includes utility functions for working with file patterns.
Author
Sergey Veneckiy
Date
2024
Definition in file args_parser.c.
Function Documentation
free_args()
void free_args (CommandLineArgs * args)
Frees memory allocated for command-line arguments.
This function releases the memory allocated for the targets array in the CommandLineArgs structure.
Parameters
args Pointer to the CommandLineArgs structure to be freed.
Definition at line 77 of file args_parser.c.
                                      {
    if (args->targets) {
        free(args->targets); // Free the targets array
        args->targets = NULL; // Set pointer to NULL to prevent double-free
    }
}
References CommandLineArgs::targets.
Referenced by main().
is_glob_pattern()
bool is_glob_pattern (const char * str)
Checks if a string is a glob pattern.
This function determines whether a given string contains wildcard characters used in glob patterns.
Parameters
str The string to check for glob pattern characters.
Returns
true if the string contains glob pattern characters, false otherwise.
Definition at line 28 of file args_parser.c.
                                      {
    // Check for the presence of wildcard characters
    return (strchr(str, '*') != NULL || strchr(str, '?') != NULL || strchr(str, '[') != NULL);
}
Referenced by is_glob_or_specific_files(), and process_target().
parse_args()
CommandLineArgs parse_args (int argc, char * argv[])
Parses command-line arguments.
This function processes the command-line arguments, setting appropriate flags in the CommandLineArgs structure and collecting non-option arguments as targets.
Parameters
argc The number of command-line arguments.
argv An array of strings containing the command-line arguments.
Returns
A CommandLineArgs structure containing the parsed arguments.
Definition at line 43 of file args_parser.c.
                                                   {
    CommandLineArgs args = {0}; // Initialize the args structure with zeros
    args.targets = malloc(sizeof(char*) * (argc - 1)); // Allocate memory for targets
    args.target_count = 0; // Initialize target count to 0
    // Loop through all arguments starting from index 1 (skip program name)
    for (int i = 1; i < argc; i++) {
        if (strcmp(argv[i], "-v") == 0 || strcmp(argv[i], "--version") == 0) {
            args.show_version = true; // Set flag to show version
        } else if (strcmp(argv[i], "-h") == 0 || strcmp(argv[i], "--help") == 0) {
            args.show_help = true; // Set flag to show help
        } else if (strcmp(argv[i], "-l") == 0 || strcmp(argv[i], "--long") == 0) {
            args.show_longlisting = true; // Set flag for long listing
        } else if (strcmp(argv[i], "-a") == 0 || strcmp(argv[i], "--analytics") == 0) {
            args.show_dir_analytics = true; // Set flag for directory analytics
        } else if (argv[i][0] == '-') {
            args.invalid_opt = argv[i]; // Store invalid option
            return args; // Return immediately on invalid option
        } else {
            args.targets[args.target_count++] = argv[i]; // Store non-option argument as target
        }
    }
    return args; // Return the populated CommandLineArgs structure
}
References CommandLineArgs::invalid_opt, CommandLineArgs::show_dir_analytics, CommandLineArgs::show_help, CommandLineArgs::show_longlisting, CommandLineArgs::show_version, CommandLineArgs::target_count, and CommandLineArgs::targets.
Referenced by main().
print_help()
void print_help (const char * program_name)
Prints the help information for facad.
This function displays usage information and available options for the facad program.
Parameters
program_name The name of the program executable.
Definition at line 102 of file args_parser.c.
                                          {
    printf("Usage: %s [OPTION] [DIRECTORY]\n", program_name);
    printf("List directory contents with colorful emojis.\n\n");
    printf("Options:\n");
    printf(" -h, --help display this help and exit\n");
    printf(" -v, --version output version information and exit\n");
    printf(" -l, --long display detailed directory listing\n");
    printf(" -a, --analytics display directory analytics\n");
    printf("\nIf DIRECTORY is not specified, the current directory is used.\n");
}
Referenced by main().
print_version()
void print_version (void)
Prints the version information of facad.
This function displays the version number of the facad program, which is defined in the config.h file.
Definition at line 90 of file args_parser.c.
                         {
    printf("facad version %s\n", VERSION); // Print version number
}
Referenced by main().