/home/honeyguide/Desktop/MyOpenSource/facad/src/git_integration.h File Reference
Header file for Git integration functionality.
#include "file_card.h"
#include "git_utils.h"
Functions
void integrate_git_status (FileCardInfo **entries, int *num_entries, const char *current_dir)
Integrates Git status information into file entries.
Detailed Description
Header file for Git integration functionality.
This file declares the interface for integrating Git status information into the file entries displayed by the facad tool. It provides the necessary function declarations and includes required dependencies.
Author
Sergey Veneckiy
Date
2024
Definition in file git_integration.h.
Function Documentation
integrate_git_status()
void integrate_git_status (FileCardInfo ** entries, int * num_entries, const char * current_dir)
Integrates Git status information into file entries.
This function retrieves the Git status for files in the current directory and updates the corresponding FileCardInfo structures with this information. It should be called after file entries are created but before they are displayed.
Parameters
entries Pointer to an array of FileCardInfo pointers. Each entry represents a file or directory.
num_entries Pointer to the number of entries in the array. This allows for potential modification of the entry count.
current_dir The current directory path. This is used to construct relative paths for Git status comparison.
Note
This function modifies the git_status field of each FileCardInfo structure in the entries array.
If the current directory is not a Git repository, this function will have no effect.
This function retrieves the Git status for files in the current directory and updates the corresponding FileCardInfo structures with this information.
Parameters
entries Pointer to an array of FileCardInfo pointers.
num_entries Pointer to the number of entries in the array.
current_dir The current directory path.
Definition at line 30 of file git_integration.c.
                                                                                             {
    // Check if the current directory is a Git repository
    if (!is_git_repository()) {
        return; // If not, return without doing anything
    }
    // Get the Git status for all files in the repository
    GitFileList git_status = get_git_status();
    // Create a copy of the current directory path
    char* base_dir = strdup(current_dir);
    // Extract the base name of the directory
    char* dir_name = basename(base_dir);
    // Iterate through all file entries
    for (int i = 0; i < *num_entries; i++) {
        // Initialize Git status as empty for each entry
        (*entries)[i].git_status[0] = '\0';
        (*entries)[i].git_status[1] = '\0';
        // Construct the relative path for the current file
        char relative_path[MAX_FILENAME];
        snprintf(relative_path, sizeof(relative_path), "%s/%s", dir_name, (*entries)[i].name);
        // Compare the file's path with Git status entries
        for (int j = 0; j < git_status.count; j++) {
            // If the paths match, update the Git status in the file entry
            if (strcmp(relative_path, git_status.files[j].filename) == 0 ||
                strcmp((*entries)[i].name, git_status.files[j].filename) == 0) {
                (*entries)[i].git_status[0] = git_status.files[j].status;
                (*entries)[i].git_status[1] = '\0';
                break; // Stop searching once a match is found
            }
        }
    }
    // Free the memory allocated for the base directory string
    free(base_dir);
}
References GitFileList::count, GitFile::filename, GitFileList::files, get_git_status(), is_git_repository(), MAX_FILENAME, and GitFile::status.
Referenced by process_directory().